# Generated by Django 5.2 on 2025-05-05 21:37

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='dietary_restrictions',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('vegan', 'Vegana'), ('vegetarian', 'Vegetariana'), ('gluten_free', 'Sin gluten'), ('lactose_free', 'Sin lactosa'), ('low_carb', 'Baja en carbohidratos'), ('keto', 'Keto'), ('paleo', 'Paleo'), ('halal', 'Halal'), ('kosher', 'Kosher'), ('nut_free', 'Sin frutos secos')], default=['none'], max_length=83),
        ),
    ]
