# Generated by Django 5.2 on 2025-05-06 15:53

import django.core.validators
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_dietary_restrictions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='activity_level',
            field=models.CharField(choices=[('sedentary', 'Sedentary'), ('light', 'Lightly Active'), ('moderate', 'Moderately Active'), ('active', 'Active'), ('very_active', 'Very Active')], default='sedentary', max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(16)]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='dietary_restrictions',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('vegan', 'Vegana'), ('vegetarian', 'Vegetariana'), ('gluten_free', 'Sin gluten'), ('lactose_free', 'Sin lactosa'), ('low_carb', 'Baja en carbohidratos'), ('keto', 'Keto'), ('paleo', 'Paleo'), ('halal', 'Halal'), ('kosher', 'Kosher'), ('nut_free', 'Sin frutos secos')], default='', max_length=83),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='goal',
            field=models.CharField(choices=[('lose_weight', 'Perder peso'), ('gain_muscle', 'Ganar músculo'), ('maintain_weight', 'Mantener peso'), ('improve_endurance', 'Mejorar resistencia'), ('increase_flexibility', 'Aumentar flexibilidad'), ('boost_energy', 'Aumentar energía'), ('reduce_stress', 'Reducir estrés')], default='maintain_weight', max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='height_cm',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='weight_kg',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
