# Generated by Django 5.2 on 2025-05-08 17:27

import django.core.validators
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='accept_terms',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(16)]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='dietary_restrictions',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('vegan', 'Vegana'), ('vegetarian', 'Vegetariana'), ('gluten_free', 'Sin gluten'), ('lactose_free', 'Sin lactosa'), ('low_carb', 'Baja en carbohidratos'), ('keto', 'Keto'), ('paleo', 'Paleo'), ('halal', 'Halal'), ('kosher', 'Kosher'), ('nut_free', 'Sin frutos secos')], default=list, max_length=83),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='height_cm',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='weight_kg',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
