# Generated by Django 5.2 on 2025-05-06 07:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_alter_mealplan_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='date',
            field=models.DateField(default=datetime.date(2025, 5, 6)),
        ),
    ]
