# Generated by Django 5.2 on 2025-05-08 03:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_alter_plan_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='date',
            field=models.DateField(default=datetime.date(2025, 5, 8)),
        ),
    ]
