# Generated by Django 5.2 on 2025-05-08 15:31

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_alter_plan_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutplan',
            old_name='exercises',
            new_name='workouts',
        ),
        migrations.AlterField(
            model_name='plan',
            name='date',
            field=models.DateField(default=datetime.date(2025, 5, 8)),
        ),
        migrations.CreateModel(
            name='TipsPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tips', models.JSONField()),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tips_plan', to='plans.plan')),
            ],
        ),
    ]
