# Generated by Django 5.2 on 2025-05-08 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_rename_exercises_workoutplan_workouts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='plan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='plans.plan'),
        ),
        migrations.AlterField(
            model_name='tipsplan',
            name='plan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='plans.plan'),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='plan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='plans.plan'),
        ),
    ]
