# Generated by Django 5.2 on 2025-05-08 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_alter_plan_date'),
        ('plans', '0006_alter_mealplan_plan_alter_tipsplan_plan_and_more'),
    ]

    operations = [
    ]
