# Generated by Django 5.2 on 2025-05-09 15:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0008_alter_plan_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='plan',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
