# Generated by Django 5.2 on 2025-05-05 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_alter_mealplan_unique_together_and_more'),
        ('progress', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyprogress',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dailyprogress',
            name='feedback',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dailyprogress',
            name='plan',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='plans.plan'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='dailyprogress',
            name='date',
        ),
        migrations.RemoveField(
            model_name='dailyprogress',
            name='feeback',
        ),
        migrations.RemoveField(
            model_name='dailyprogress',
            name='recommended_meals',
        ),
        migrations.RemoveField(
            model_name='dailyprogress',
            name='recommended_workout',
        ),
        migrations.RemoveField(
            model_name='dailyprogress',
            name='user',
        ),
    ]
