# Generated by Django 5.2 on 2025-05-06 15:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0004_alter_dailyprogress_mood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyprogress',
            name='feedback',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='dailyprogress',
            name='weight_kg',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
