# Generated by Django 5.2 on 2025-05-06 20:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0005_alter_dailyprogress_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyprogress',
            name='bmi',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
