# Generated by Django 5.2 on 2025-05-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0006_dailyprogress_bmi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyprogress',
            name='feedback',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
