# Generated by Django 5.2 on 2025-05-09 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0007_alter_dailyprogress_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyProgress',
        ),
    ]
