name: Docker Image Build and Push to ACR

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure Container Registry
        run: |
          echo "${{ secrets.ACR_PASSWORD }}" | docker login fitow.azurecr.io -u ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Build Docker image
        run: |
          IMAGE_TAG=$(date +'%Y-%m-%d')_${{ github.run_number }}
          docker build -f Dockerfile -t fitow.azurecr.io/fitflow:$IMAGE_TAG .

      - name: Push image to ACR
        run: |
          IMAGE_TAG=$(date +'%Y-%m-%d')_${{ github.run_number }}
          docker push fitow.azurecr.io/fitflow:$IMAGE_TAG
